# Translations web gui
# This will insert to `config/i18n/{lang}.json`, under key `Gui`

Login:
  Login:
  LoginError:

Aside:
  Install:
  Home:
  Develop:
  Performance:
  Setting:
  AddAlas:

Button:
  Start:
  Stop:
  ScrollON:
  ScrollOFF:
  DashboardON:
  DashboardOFF:
  ClearLog:
  Setting:
  CheckUpdate:
  ClickToUpdate:
  RetryUpdate:
  CancelUpdate:

Toast:
  DisableTranslateMode:
  ConfigSaved:
  AlasIsRunning:
  ClickToUpdate:
  AlasRestart:
  ReloadEnabled:

Status:
  Running:
  Inactive:
  Warning:
  Updating:

MenuAlas:
  Overview:
  Log:

MenuDevelop:
  HomePage:
  Translate:
  Update:
  Remote:
  Utils:
  RaiseException:
  ForceRestart:

Overview:
  Scheduler:
  Dashboard:
  Log:
  Running:
  Pending:
  Waiting:
  NoTask:
  SecondsAgo:
  MinutesAgo:
  HoursAgo:
  DaysAgo:
  MonthsAgo:
  YearsAgo:
  NoData:
  Oil:
  Coin:
  Gem:
  Cube:
  Pt:
  YellowCoin:
  PurpleCoin:
  ActionPoint:
  Merit:
  Medal:
  Core:
  GuildCoin:

AddAlas:
  PopupTitle:
  NewName:
  CopyFrom:
  Confirm:
  FileExist:
  InvalidChar:
  InvalidPrefixTemplate:

Update:
  UpToDate:
  HaveUpdate:
  UpdateStart:
  UpdateWait:
  UpdateRun:
  UpdateSuccess:
  UpdateFailed:
  UpdateChecking:
  UpdateCancel:
  UpdateFinish:
  Local:
  Upstream:
  Author:
  Time:
  Message:
  DisabledWarn:
  DetailedHistory:

Remote:
  Running:
  NotRunning:
  NotEnable:
  EntryPoint:
  ConfigureHint:
  SSHNotInstall:

Text:
  InvalidFeedBack:
  Clear: